name: E2E Tests
on:
  workflow_dispatch:
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Chekout Code
      uses: actions/checkout@v5
    
    - name: Set uo Node
      uses: actions/setup-node@v4
      with: 
        node-version: 22
        cache: 'npm'
    
    - name: Install WebApp dependencies
      run: npm install
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install Test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Browser Lib Init
      run: rfbrowser init

    - name: Run WebApp
      run: npm start &
      env: 
        CI: true
    
    - name: Wait for WebAPP
      run: npx wait-on http://localhost:3000 --timeout=60000

    - name: Run E2E Tests
      run: robot -d ./logs robot/tests

    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-results-chromium
        path: logs/
